### ISSUE TITLE
Some apps with updated material components cannot be completely re-themed through "Force per app theme"

### ISSUE THREAD

**Issue by Username1-a** [Mahmud0808/ColorBlendr#67] opened 2024-04-08 16:31 UTC
Looks like some apps that have updated material components cannot be themed through the "force per app theme" menu, the app background stays the same (doesn't follow Colorblendr's Black theme for example), even after force closing the app. 

Examples of such apps:

   1. Copy SMS Code (https://github.com/jd1378/otphelper):
       —Older version 1.13.1 with old material components repaints by Colorblendr completely (including the background brightness), without using the "force per app theme"
       —While later updated versions (using most recent v1.13.4 in example) with updated material components cannot be completely repainted by Colorblendr even with "force per app theme" enabled for the app;

   2. MRepo (https://github.com/MRepoApp/MRepo):
        —Older version 2.4.3 repaints completely
        —While later updated versions (using most recent v2.4.6 in example) cannot be completely repainted even with "force per app theme";
  
   3. Open Video Editor (https://github.com/devhyper/open-video-editor):
        —Older version 1.0.2 repaints completely
        —While later updated versions (using most recent v1.1.1 in example) cannot be completely repainted even with "force per app theme";

But for example
         LogFox (https://github.com/F0x1d/LogFox) in newer versions with updated material components repaints just fine (so, with it's background) when using "force per app theme":
         —Older version 1.5.1 with old material components repaints completely without using "force per app theme"
         —Later versions with updated material components (using most recent LogFox v1.5.7) repaints completely using "force per app theme"

Just thought I'd let you know

(I'm using EvoX ROM, Android 13 QPR3, Colorblendr v1.3)

**Comment by Mahmud0808** [comment] 2024-04-17 18:12
<p float="left">
  <img src="https://github.com/Mahmud0808/ColorBlendr/assets/29881338/fa0a9f91-eb65-41d7-99ae-28ff575d7a40" width="33%" />
  <img src="https://github.com/Mahmud0808/ColorBlendr/assets/29881338/4200be7f-1371-450a-a150-d6483da22dfc" width="33%" /> 
  <img src="https://github.com/Mahmud0808/ColorBlendr/assets/29881338/6ca21288-3065-4e28-bfab-b01e005c3700" width="33%" />
</p>

So I just got some time to check this issue out. All 3 apps you mentioned are themed perfectly without even having to select them in force per app theme list. Hence closing this issue as it isn't reproducible in my case.

**Closed by Mahmud0808** 2024-04-17 18:12 UTC
Labels: bug

**Comment by Mahmud0808** [comment] 2024-04-19 18:16
Some apps don't allow overlaying so these will automatically get unselected after selecting. If this issue is reproducible in more roms (and by me too), then I can look into it. Otherwise can't help.

**Comment by Henry-Hiles** [comment] 2024-04-24 05:25
> Some apps don't allow overlaying so these will automatically get unselected after selecting. If this issue is reproducible in more roms (and by me too), then I can look into it. Otherwise can't help.

If I know an app developer, how can they enable overlaying for their app

**Comment by Mahmud0808** [comment] 2024-04-24 08:32
> > Some apps don't allow overlaying so these will automatically get unselected after selecting. If this issue is reproducible in more roms (and by me too), then I can look into it. Otherwise can't help.
> 
> If I know an app developer, how can they enable overlaying for their app? Thx.

I don't know for sure. As far as I know, split apks don't support overlaying (not sure about this). Also apps like playstore, facebook, whatsapp etc are unthemable because of resource obfuscation.
