### ISSUE TITLE
It breaks the Monet themes 

### ISSUE THREAD

**Issue by FL4R3ZZZ** [Mahmud0808/ColorBlendr#103] opened 2024-07-14 15:34 UTC
After using the app regardless of having it on or even installed the Monet colors will not change 
Only if I change them manually on the app
The only exit I'm seeing is factory resetting the phone and I really don't want to 
On Android 14

**Comment by Mahmud0808** [comment] 2024-07-14 15:36
duplicate of #85

**Closed by Mahmud0808** 2024-07-14 15:36 UTC
